spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true # data initial, 메모리모드에서 사용
  config:
    import:
      - classpath:application-mail.yml
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

file:
  dir: "d:/outflearnstorage/"
