package io.jeidiiy.outflearn.mock;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.jeidiiy.outflearn.course.domain.Course;
import io.jeidiiy.outflearn.course.service.port.CourseRepository;

public class FakeCourseRepository implements CourseRepository {
	private final List<Course> store = new ArrayList<>();
	private Long autoGeneratedId = 1L;

	@Override
	public Course save(Course course) {
		if (isNewCourse(course)) {
			Course newCourse = Course.builder()
				.id(autoGeneratedId++)
				.title(course.getTitle())
				.description(course.getDescription())
				.creator(course.getCreator())
				.build();
			store.add(newCourse);
			return newCourse;
		}

		store.removeIf(elem -> Objects.equals(elem.getId(), course.getId()));
		store.add(course);
		return course;
	}

	private boolean isNewCourse(Course course) {
		return course.getId() == null || course.getId() == 0L;
	}
}
